### ISSUE TITLE
Periodic Boundary Conditions

### ISSUE THREAD

**Issue by wackywendell** [qhull/qhull#10]
Would it be possible to implement containers with periodic boundary conditions?

**Comment by qhull** [comment]
At 04:26 PM 3/31/2016, Wendell Smith wrote:

>Would it be possible to implement containers 
>with periodic boundary conditions?

You would need to write code that interfaces with 
Qhull.  I found the following on the web which 
may be similar to what you want.   It may provide 
hints on how to transform the periodic boundary 
conditions into Qhull's data structures and computations.
     http://math.lbl.gov/voro++/doc/refman/

Since voro++ computes the Voronoi diagram 
directly, the transformation from voro++ to 
qhull's convex hulls may be tricky.  I'd ask a 
specialist in Voronoi diagrams or computational geometry.

I hope your project goes well.

                                 --Brad

**Comment by cbbarber** [comment]
Closing
