### ISSUE TITLE
typo in qh_initflags: Q17 is matched instead of Q15

### ISSUE THREAD

**Issue by djerius** [qhull/qhull#140]
The match for option `Q15` mistakenly matches `Q17`:

https://github.com/qhull/qhull/blob/89341b937a90ae8dc19e13a2bd4225d3c9abe4c2/src/libqhull_r/global_r.c#L1199-L1202

**Comment by cbbarber** [comment]
Good catch.   This error occurred during the development of 2019.1.   At first, duplicate ridges were checked while merging. There was an option Q17 to turn off this check since it was expensive.  Detecting duplicate ridges turned out to be less valuable than expected. The option was reversed and other test options were abandoned.  

I'll restore Q15 as Q17 and update the documentation.  

The next release will add a test of this option.

**Comment by djerius** [comment]
Thanks; FWIW this was picked up while writing a Perl interface to qhull to try and catch option errors up front before invoking qhull.  Alpha quality and just wrapping the executable at the moment: 

https://metacpan.org/release/DJERIUS/Qhull-0.01

**Comment by cbbarber** [comment]
Changed Q15 to Q17 in multiple locations. All changes in documentation.  qh_initflags in global.c: has tested for 'Q17' since Qhull-2019.0.1.

**Comment by cbbarber** [comment]
Closed with tag 8.1-alpha4
