### ISSUE TITLE
Documentation is installed in include dir

### ISSUE THREAD

**Issue by haudren** [qhull/qhull#23]
The documentation for `libqhull_r` and `libqhull` is installed in `${INCLUDE_INSTALL_DIR}/libqhull_r` and `${INCLUDE_INSTALL_DIR}/libqhull`respectively. I believe those `htm` files should rather go in `${DOC_INSTALL_DIR}`.

**Comment by cbbarber** [comment]
The '.htm' files in libqhull/ and libqhull_r are low-level function documentation for the corresponding source files (e.g., qh-poly_r.htm, poly_r.h,  and poly_r.c) in the same directory.     The .htm files contain links to the source files.

For example
--------------
<li><a href="poly_r.h#DUPLICATEridge">DUPLICATEridge</a>
special value for facet-&gt;neighbor to indicate
a duplicate ridge </li>
--------------

When written, browsers would read the source files as html, making for quick navigation between code and documentation.

For example
--------------
/*<html><pre>  -<a                             href="qh-poly_r.htm"
  >-------------------------------</a><a name="TOP">-</a>

   poly2_r.c
   implements polygons and simplicies
...
--------------

Unfortunately, new browsers refuse to view disk files as html.    An .htaccess file on www.qhull.org allows IE and Chrome to view these files.  I have not figured out how to make Firefox do the same.   Any suggestions are welcome.
     http://www.qhull.org/src/libqhull_r/index.htm

The Qhull manual and other html/ files install in DOC_INSTALL_DIR.   

For now anyway, function documentation will remain in the source directories.  If moved elsewhere, they would need customization for access to the corresponding source files.   Let me know if you prefer otherwise.

**Comment by cbbarber** [comment]
Fixed web access by Firefox.   For example, click on "Global" then "qh_initflags" in
    http://www.qhull.org/src/libqhull_r/index.htm
    http://www.qhull.org/src/libqhull_r/global_r.c#initflags

Closed with explanation why source documentation for Qhull is in a src directory instead of DOC_INSTALL_DIR
