### ISSUE TITLE
Halfspace intersections with C++ interface

### ISSUE THREAD

**Issue by maweigert** [qhull/qhull#34]
Hi, 

I'm trying to compute halfspace intersections with the C++ interface following [this test example](https://github.com/qhull/qhull/blame/master/src/qhulltest/Qhull_test.cpp). 
If I however try the simple case of an unit square in 2D

``` c++
//halfspaces defining the unitsquare [0,1] x [0,1] 
double normals[] = {-1,  0,  0,
                     0, -1,  0,
                     1,  0, -1,
                     0,  1, -1 };
Coordinates feasible(std::vector<double>({.5,.5}));
Qhull q;
q.setFeasiblePoint(feasible);
q.runQhull("unit square", 3, 4, normals, "H");
std::cout<< q.vertexList() << std::endl;
```
I get the following output 
```
- p3 (v2):  0 2
- p1 (v4):  0 -2
- p0 (v0):  -2 0
- p2 (v1):  2 0
```
which is a bit unexpected. I guess I am missing something basic (e.g. if I change the feasible point slightly, the resulting vertices change vastly). 
Is that behaviour expected, and if so, what would be the correct way to do it?  
Any help is appreciated!

**Comment by maweigert** [comment]
Ok, I figured it out - the vertex/face list is still in the dual, which one has to convert to yield the real intersection points of the halfspaces (mentioned [here](https://github.com/scipy/scipy/blob/master/scipy/spatial/qhull.pyx#L2724)). After doing so, everything works as expected (my bad). For future reference:   

```c++ 
// construct halfspace intersection points from qhull output
// see https://github.com/scipy/scipy/blob/master/scipy/spatial/qhull.pyx#L2724
// intersections = dual_equations[:, :-1]/-dual_equations[:, -1:] + interior_points

std::vector<std::array<coordT,2>> intersections;

QhullFacetListIterator it(q.facetList());

while(it.hasNext()){

  std::array<coordT,2> inter;
  QhullHyperplane plane = it.next().hyperplane();

  for (int i = 0; i < dim; ++i)
	inter[i] = -plane[i]/plane.offset() + interior_point[i];

  intersections.push_back(inter);
 }

for (auto it = intersections.begin(); it != intersections.end(); ++it) 
  cout<< "intersection point: " << (*it)[0] << " "<<  (*it)[1]<< endl;

```

**Comment by cbbarber** [comment]
Hi Martin,

Good work.  Please consider adding qhull.pyx to qhull/eg and improving libqhullcpp.  'libqhullcpp' is not under active development.  Except for user_eg3.cpp and qhulltest.cpp, none of my code uses libqhullcpp.

I noticed your _find_simplex() comment that qh_findbestfacet doesn't always return the simplex containing the point given.  When qh_findbestfacet is called with the 3rd parameter, 'bestoutside', qh_ALL (aka true or 1), it returns the facet that maximizes the distance.  This facet corresponds to the simplex containing the point.   An exception is tricoplanar facets (see the qh_findbestfacet header).   

My guess is that problem is Qhull.plane_distance.   It should project the point 'xi' to the paraboloid (qh_setdelaunay), and then test this projected point to each of the facets.

Checking the computation (4 digits precision) for the third facet gives 0.0174 while your value was 0.01050.  The second facet (containing the point) gives 0.1943.

Third facet (3, 2, 0) has a hyperplane of
   0.6857842719055222 0.243720874801536 -0.6857842719055222 -5.549439971493885e-15
or
  0.6858, 0.2437, -0.6858, 0.0

Projected test point is
0.9999    0.1 1.00980001
or
0.9999    0.1 1.010

inner product plus offset (0.0) is 
0.6857 + 0.0244 - 0.6927 + 0.0 = 0.0174

Second facet (4, 2, 1)  has a hyperplane of
0.9995324089620921 0.02162132551946809 -0.02162132551946809 -0.9779110834426296
or
0.9995 0.02161 -0.02162 -0.9779

Point is
0.9999    0.1 1.010

inner product plus offset (-0.9779) is 
0.9994 + 0.00216 - 0.218 -0.9779 = 0.19434

Qhull 'o' gives the triangulated paraboloid, while 'Fo' gives the outer planes.   'x.5' is your points while 'x.6' includes the test point.   The facet order is the same for x.5 as for your test case.

KELWYN-/local/qhull/bin> qhull d < x.5.txt o Fo
3
5 5 7
     0      0      0
     1      1      2
     1      0      1
0.99189033 0.37674127 1.125780411268722
0.99440079 0.45182168 1.192975761670647
3 4 1 0
3 4 2 1
3 2 3 0
3 3 4 0
3 4 3 2
4
5
0.2876909082978237 0.7913107940902221 -0.5395008511940229 -5.549439971493885e-15
0.9995324089620921 0.02162132551946809 -0.02162132551946809 -0.9779110834426296
0.6857842719055222 0.243720874801536 -0.6857842719055222 -5.549439971493885e-15
0.5195904624796275 0.5600931793295906 -0.6452297124037901 -5.549439971493885e-15
0.9937905494337299 0.05389207366932479 -0.09734468784594869 -0.8964458615877867
KELWYN-/local/qhull/bin> qhull d < x.6 o
3
6 7 10
     0      0      0
     1      1      2
     1      0      1
0.99189033 0.37674127 1.125780411268722
0.99440079 0.45182168 1.192975761670647
0.9999    0.1 1.00980001
3 4 1 0
3 2 5 0
3 5 2 1
3 4 5 1
3 3 4 0
3 5 3 0
3 3 5 4

Note that qh_findbestfacet is rather inefficient.   It needs to search all facets if the directed search reports an 'inside' point.  Qhull avoids searching all facets by  maintaining an 'outsideset' for each facet.

                                        --Brad


At 11:18 AM 01/24/2019, you wrote:

**Comment by maweigert** [comment]
Hi Brad, 

thanks for the fast reply! 
Alas, I'm not related to the qhull.pyx bindings - I just started to dig into qhull and merely saw the halfspace intersection calculation in the scipy repo and adapted it for my need. Maybe your explanation might be interesting for @pv (via git blame).  
Btw, I really like qhull's C++ bindings! :)
