### ISSUE TITLE
QHull doesn't compute furthestdist

### ISSUE THREAD

**Issue by yurivict** [qhull/qhull#39]
My ```qhull_r``` library and user code are built with ```#define qh_COMPUTEfurthest 0``` which seems to mean that it is pre-computed and stored with the facets. However, the ```furthestdist``` field at this point https://github.com/yurivict/ChemWiz/blob/master/molecule-qhull.cpp#L35 is always zero.

Why doesn't it compute ```furthestdist```?

**Comment by cbbarber** [comment]
Hi Yuri,

qh_new_qhull computes the convex hull of the input points.  During the computation, it tracks the distance to the furthest point of each facet's outsideset.  When done, f.outsideset is empty for each facet, and f.furthestdist==0.0.    Since your code tests f.furthestdist after running qh_new_qhull, it will always be zero.

To find facets with a non-zero f.furthestdist, stop the construction of the convex hull with options 'TCn' or 'TVn'.  If a point is "outside" a facet, it is waiting to be processed by qh_addpoint. 

                                        --Brad

src/libqhull_r/libqhull_r.h

struct facetT {
#if !qh_COMPUTEfurthest
  coordT   furthestdist;/* distance to furthest point of outsideset */
#endif
...
  setT    *outsideset;  /* set of points outside this facet
                           if non-empty, last point is furthest
                           if NARROWhull, includes coplanars for partitioning*/
