### ISSUE TITLE
Moving version 2018.0.1 to its own branch

### ISSUE THREAD

**Issue by korrat** [qhull/qhull#42]
Since you asked for advice on how to move version 2018.0.1 to a new branch in the wiki, I came up with the following procedure:

```bash
# Ensure you have a clean working directory

# Make sure master is up to date
$ git fetch

# Create the new branch for version 2018.0.1
$ git branch --no-track 2018.0.1 origin/master

# Reset master to version 7.2.1
$ git checkout master && git reset --hard v7.2.1

# Publish the changes to master
$ git checkout master && git push --force-with-lease

# Publish the new branch
$ git checkout 2018.0.1 && git push --set-upstream origin 2018.0.1
```

This will move all commits since v7.2.1 to a new branch 2018.0.1.

Every contributor must also reset their local master after these changes. This is done with

```bash
$ git fetch
$ git checkout master && git reset --hard v7.2.1
```

**Comment by cbbarber** [comment]
Many thanks Korrat for your good advice.  I'll save it in case it is needed later.

Instead of branching 2018.0.1, I'll post a release candidate for 2019.1.  It continues the work started with 2018.0.1, but it moves the unfinished part into an experimental option ('Q14'). 

                                        --Brad

At 07:48 AM 04/12/2019, you wrote:

**Comment by cbbarber** [comment]
Closing.   Posted 2019.0.1 at the end of May.

Qhull 2019.1 is expected by the end of June.
