### ISSUE TITLE
qhalf strange intersection points

### ISSUE THREAD

**Issue by ehuang3** [qhull/qhull#50]
With the following input:
```
2 1
4.5 0.0
3
4
0 1 -4
0 1 -1
-1 0 1
-1 0 4
```
as `tests/data`, I tried to compute the intersection points with
```
qhalf Fp Fn < tests/data
```
and it returns
```
2
4
     4      1 
-10.101 -10.101 
-10.101 -10.101 
-10.101 -10.101 
4
2 2 1
2 3 0
2 0 3
2 1 2
```
But clearly the point (-10.101, -10.101) is not within the halfspaces [-1, 0]x + 1 <= 0 or [-1, 0]x + 4 <= 0.

What is going on?

**Comment by cbbarber** [comment]
The documentation explains -10.101, but you need to hunt for it.   I'll add additional notes.  

It helps to graph the input.   In this case, the first and second pairs of hyperplanes are parallel to each other.  The intersection of the corresponding halfspaces is unbounded.  It includes your interior point [4.5, 0.0].

For half space intersection, option 'Fp' returns the intersection points.  The coordinates [-10.101, -10.101] indicate an unbounded intersection.   

Option 'Fv' lists the intersection points for each halfspace.   For your input, the output for 'Fv' is

4
2 1 3
2 1 0
2 2 3
2 2 0

If you identify the input hyperplanes as A,B,C,D instead of 0,1,2,3, the first intersection point [4, 1] is B-D.   The second intersection point is unbounded since hyperplanes B-A are parallel to each other.   Similarly hyperplanes D-C are parallel.   The last unbounded intersection point is for hyperplanes C-A.  They intersect at [1, 4] which is outside of the halfspace intersection.

If you add halfspace [1, -1, -8] to bound the intersection, 'qhalf Fp Fn' produces (with roundoff)

2
3
     4 -4.000000000000001
     4      1
     9      1
3
2 1 2
2 0 2
2 0 1

			--Brad
