### ISSUE TITLE
Computing the volume of a convex polytope when the vertices are known

### ISSUE THREAD

**Issue by mttk** [qhull/qhull#51]
First of all, thanks for the effort, qhull has been great help.

I have problem where I have a set of points which I know for certain to be vertices of a convex polytope, and I would like to compute the volume of that polytope. The issue when using qhull (from python, via the scipy.spatial interface) arises when the dimension of the space & the number of vertices gets large, as mentioned in the performance notes. I was wondering whether it is possible to stretch the limitations a bit by providing the vertices, or is the runtime dominated by the facet search? 
The problem could also be simplified a bit as I believe I could also compute the facets.

The dimensionality ranges from 5 - ~35 -dim, and the number of points grows with the dimensionality.

Concretely, the problem I have is that I want to determine the ratio (only the ratio) of volumes of convex polytopes defined by the intersection of a hyperplane and the unit (n-1)-simplex in Rn. I would appreciate any help and pointers you might provide!

**Comment by cbbarber** [comment]
The problem is that the size of the convex hull grows rapidly as the dimension increases.   Knowing that all input points are extreme points (i.e., vertices) does not help since the culling of interior points happens quickly.

If you know the facets, it is straight forward to sum the volume of each facet to an interior point.

For Qhull, the dominant costs in high-D are hyperplane computation and memory access (especially when virtual memory is needed).   Hyperplanes are created as a cone around a new vertex.   They could be created in parallel.  An incremental computation should be faster, but may lead to additional round-off error.

Option 'TFn' is a good way to monitor memory access cost.   Qhull typically takes about the same amount of time to add each point.

The computational geometry community may know of other approaches.
    http://www.computational-geometry.org/

**Comment by mttk** [comment]
Thanks a lot!
