### ISSUE TITLE
Linking error

### ISSUE THREAD

**Issue by jmirabel** [qhull/qhull#62]
I built qhull from sources (version 2019.1) and intend to use it in a C++ project that uses CMake. I work on ubuntu 18.04.

 When linking to libqhullcpp.a, i get the following error:
> /usr/bin/ld: ../qhull-install/lib/libqhullcpp.a(Qhull.cpp.o): relocation R_X86_64_PC32 against symbol `_ZSt4cerr@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC

I tried using the CMake target *Qhull::qhullcpp*.

Am I doing something wrong ?

**Comment by jmirabel** [comment]
Note that building a shared library instead of a static one for qhullcpp works.

**Comment by cbbarber** [comment]
Hi Joseph,

Searching for "relocation R_X86_64_PC32 against symbol" brings up several useful links, particularly
   https://stackoverflow.com/questions/19768267/relocation-r-x86-64-32s-against-linking-error
   https://stackoverflow.com/questions/6093547/what-do-r-x86-64-32s-and-r-x86-64-64-relocation-mean

It appears that 'libqhullcpp.a' was built on an AMD64 host as a 32-bit static library without position-independent code (option -fPIC).   This is the default options for qhull/Makefile

Agner Fog has a detailed discussion of position-independent code in section 14.12 of https://www.agner.org/optimize/optimizing_cpp.pdf

For 32-bit code, he recommends static linking with -fno-pic.   For 64-bit code, he recommends linking with -fpic.

Qhull saves significant memory when compiled as 32-bit code.   That's why it is the default in the Makefiles (symbol 'M32').   A future version of Qhull will alleviate the memory issues with 64-bit code.   Currently Qhull works fine as 64-bit code, but it consumes more memory than necessary.

I welcome suggestions for default Makefile options (CC_OPTS1 and CXX_OPTS1).   The same for CMakeLists options, particularly set_target_properties(${qhull_CPP}).

Others have run into similar issues.  I'm replying to your issue first.

                                                     --Brad

By default CMakeLists will build as 64-bit code on 64-bit hosts.

**Comment by jmirabel** [comment]
Thanks for the insights. I tried to find information to look it up but I did see the link you provided.

**Comment by cbbarber** [comment]
Hi Joseph,
With help from the github community, the 2020.1 release of Qhull uses -fpic by default.  Please give it a try.
          https://github.com/qhull/qhull/wiki

**Comment by jmirabel** [comment]
Thank you for the follow up. I will give it a try.
