### ISSUE TITLE
Problem with creating static, shared, and dynamic library

### ISSUE THREAD

**Issue by VOLCANIC-9** [qhull/qhull#82]
I read the whole readme (http://www.qhull.org/README.txt) repeatedly. Then, I tried to build the library according to the proposed method.
I achieved almost nothing.
Since the whole process is written for Linux and Unix, not Windows (even the authors themselves have confirmed this).
Can anyone provide a recipe in detail for building or using it under Windows?
I want to add it to a code as an external library or I can have the build library file of each section.

**Comment by cbbarber** [comment]
I'm sorry you had trouble building Qhull.   Qhull is developed and maintained on Windows with Visual C++.   It is a console application instead of a GUI.   

If you have Visual C++ from Microsoft, load the Qhull solution file (qhull-32.sln or qhull-64.sln).  See "Compiling Qhull with Microsoft Visual C++" in README.txt.

The Makefile and CMakeLists.txt builds are Unix-based.  They do not work on the Windows command shell.  To use these  builds, install a Unix command shell.   If you have Windows 10, a good command shell is Git for Windows.   You will also need a C compiler such as gcc.   A good choice is  mingw.   See "Compiling Qhull with mingw/gcc on Windows".  

If you have an earlier version of Windows, http://www.qhull.org/road, is a standalone, Unix command shell based on MSYS.   You will need a C compiler.

If you are unfamiliar with Unix and makefiles, I recommend finding someone to help.  Unix is an excellent system, but it takes a while to understand.

I hope this helps.

                        --Brad

**Comment by VOLCANIC-9** [comment]
Thanks for responsibility. 
I build it based on "Compiling Qhull with Microsoft Visual C++" in README.txt. 
First, please update the build process in this part. Clearly, installing VSC++11 on the new version of Microsoft visual studio doesn't lead to employing "vs100" in "Retarget solution".
Indeed, making the project based on the new version of Microsoft visual studio will be very helpful.
Second, after the process is done, a number of files are formed.
There is clearly a ".lib" file inside these files. Now my questions are:
Can the library formed under the name of "qhullstatic_d" be used to build a Voronoi diagram?
Is this use only by calling this file or should a file with another name be called for example "qVoronoi " from the build file?
I could not find the dynamic and shared part of the library files, are these files also produced according to this method?
As a final question, a number of ".dll" and ".exe" files are also in the middle folder, can ".dll" be extracted from these ".exe" files?

**Comment by cbbarber** [comment]
qhullstatic_d.lib is the debug version of non-reentrant qhull for static linking.  It includes all of the Qhull functions.   It does not include the C++ interface.  qhullstatic_r.lib or qullstatic_rd.lib are better choices.  

The shared libraries are built for reentrant Qhull (e.g., qhull_r.dll).

A .dll cannot be extracted from an .exe file.
